### ISSUE TITLE
Unknown error with bungee portal 

### ISSUE THREAD

**Issue by Champion0912** [trentech/ProjectPortals#115]
I have created a portal which takes me onto a different server in our Bungee network.
The error occurs once I enter it.
The command which is ran with the portal entry is executed, then I get logged out (timed out maybe?) and have to rejoin. upon rejoining I am still inside the portal so my game crashes again.
I need to stop the server and remove the plugin to get out of the loop.

I can confirm that running /server and joining the server like usual works just fine.

Error: https://pastebin.com/RTzYaqm7
Possible related topic and fix written as first comment (??): https://github.com/NucleusPowered/Nucleus/issues/1030

Please give me a reply once you've read this.
If it can't be fixed quick and easy I'll have to come back to PJP once it is.

**Comment by SenpaiDerp** [comment]
I have the same error :D I've read of 'issues' in the past being solved by downgrading versions, haven't tried it yet though.

**Comment by Champion0912** [comment]
Still having this issue with Illegal Async PhaseTracker Access..
Any updates at all? :)

**Comment by trentech** [comment]
Are you using the latest build?

https://trentech.org/jenkins/job/ProjectPortals/

**Comment by Champion0912** [comment]
I'm using projectportals-7.2.0-0.15.0, and projectportals-7.2.0-0.15.0.

**Comment by Champion0912** [comment]
Command used was: /Portal create testName factions -b
The 'factions' name is the same as if I do /server.

**Comment by trentech** [comment]
Can you send a new log with the errors mentioned?

**Comment by Champion0912** [comment]
Update: After going at it again with both newest versions of the plugins I'm getting a different error :O

Now I do the same command. Everything works like a charm. I'm filling in the portal and do the same /portal save, but now it just throws this error and doesn't create the portal. https://pastebin.com/JJL6uHCR

**Comment by Champion0912** [comment]
I can also confirm that the newest versions of both pjp and pjc is installed on the target server.

**Comment by trentech** [comment]
Looks to be related to your config. Try removing your current config and let pjp generate a new one

**Comment by Champion0912** [comment]
Woah, fixed!
