### ISSUE TITLE
Particle are not set on restart server, DataSerializable issue

### ISSUE THREAD

**Issue by alimtunc** [trentech/ProjectPortals#117]
Hi, I found this issue where particle are not set when I restart the server because you get a null value when you trying to get the effect data class. The container has the EffectClass data but "container.getSerializable()" seems to not work, I tried few way to get a clean class, can't get it worked.. I never stored data like that before. If I have time later, I'll try to fix it but now at least, you know where is the problem.

https://github.com/trentech/ProjectPortals/blob/78ae964a88997e2954479c36cd991571c85585b6/src/main/java/com/gmail/trentech/pjp/portal/features/Properties.java#L152

**Comment by trentech** [comment]
f7e340fc9a07bc51627fdb74ae4a75fc9034f4d6
