### ISSUE TITLE
Server locks up when using "random" portal feature.

### ISSUE THREAD

**Issue by tenten8401** [trentech/ProjectPortals#13]
My rig should be powerful enough to handle a RandomTP, sporting an i7 4790k and 32 GB of ram, and yet the server crashes when using the random feature. Not sure what's up with this.

**Comment by trentech** [comment]
The problem is the checks it takes to retrieve a "safe" location. I'm going to be pushing an update that might help improve performance

**Comment by trentech** [comment]
Update to latest and let me know
