### ISSUE TITLE
Creating portal error

### ISSUE THREAD

**Issue by YOYOK9** [trentech/ProjectPortals#17]
I am trying to make a portal for across bungee servers, I am using the waterfall port of bungeecord. The problem that is occurring is when I try to save the internal part of the portal:
 I am able to build the portal frame and save it but when I fill in the portal frame with a block (in this case obsidian) and try to save it I get an error: http://pastebin.com/Y8qemk0N

Pictures:
http://puu.sh/ro4c3/302ff11dfa.png
http://puu.sh/ro4c3/302ff11dfa.png

Minecraft: 1.10.2
Mods:
Sponge version: 1.10.2-2092-5.0.0-BETA-1753
Project Portals: 4.2.0-0.11.4
SpongyCord: 1.1.0
Essentialcmds: 1.10.2-81.14-universal

**Comment by trentech** [comment]
You need to pre release for that version of Sponge
