### ISSUE TITLE
The pjp.cmd.home will override the essentialcmds.home.use

### ISSUE THREAD

**Issue by honyihon** [trentech/ProjectPortals#2]
If we need to set the cross-world home we will use the /pjp home create command (we need cross-world permission to the home in different world)
but you just override the essential command (no need cross-world permission)
two plug-in shouldn't use same home command ,especially this important command

**Comment by trentech** [comment]
One plugin does not dictate the commands another plugin can use. Command conflicts are to be resolved by the Sponge server owner.

https://forums.spongepowered.org/t/conflicting-plugin-commands-look-no-further/11011
