### ISSUE TITLE
Portal formation error

### ISSUE THREAD

**Issue by YOYOK9** [trentech/ProjectPortals#22]
So after doing the last /portal save I see the particles from the portal spawning. However the portal doesn't actually appear. After trying multiple times still received the same result. 

Console portal creation log:
https://gist.github.com/YOYOK9/8eee80556bbcd605c0335557584904e5

PjP: 5.0.0-0.13.1
Sponge: 1.10.2-2107-6.0.0-BETA-1832
forge: 2107
MC: 1.10.2

**Comment by trentech** [comment]
Delete the data file in the data.mv.db config directory and try again.

**Comment by YOYOK9** [comment]
It worked thank you for your quick response. 

However if I may recommend making an update that fixes the "Particles Effects Settings" in the config. I read in on the sponge plugin page about changing "type: "SPELL_WHICH" to "WHICH_SPELL" and "REDSTONE" to "REDSTONE_DUST" I caught this error but not sure if others will actually "read".

Thank you for your time :)

**Comment by trentech** [comment]
I've already done this. I thought it was already in the latest release but I guess it's not.

**Comment by YOYOK9** [comment]
oh. maybe I missed that. Updated the 23/October.
