### ISSUE TITLE
[Server thread/ERROR] [Sponge]: The Scheduler tried to run the task pjp-S-4684 owned by Plugin

### ISSUE THREAD

**Issue by ziceptor** [trentech/ProjectPortals#26]
forge-1.10.2-12.18.2.2098-universal.jar
spongeforge-1.10.2-2098-5.1.0-BETA-1814.jar
projectportals-5.1.0-0.13.3.jar

http://pastebin.com/wzDeDQk8

**Comment by trentech** [comment]
Like I said before update to latest SpongeForge

**Comment by ziceptor** [comment]
But this is the latest version: spongeforge-1.10.2-2098-5.1.0-BETA-1814.jar
Or do you mean the last API6? Not all plugins support API6. And some of your. Can explicitly specify which version to use?

**Comment by trentech** [comment]
72f8dc916f03b643eec9198606510f8dd984515b
