### ISSUE TITLE
Need to be able to disable the /back command. 

### ISSUE THREAD

**Issue by ProxyNeko** [trentech/ProjectPortals#27]
Can you add the /back command into the modules section of the config we are using another plugin to deal with homes permissions and other things and we can disable everything else that conflicts apart from /back and I would rather not have to remove this plugin to avoid moaning players :s 

Thanks in advance!

**Comment by trentech** [comment]
I can add this but I will warn you, using a /back command from another plugin may not get along with portals.

Maybe you could explain to me where this command needs improvement

**Comment by NoxIceCat** [comment]
Well for players to go home from places like there last warp/tp/dimensional change we had been using nucleus and when I installed project portals on one of the played on servers we found out it had /back too so I added the permission node so they could use either command but it said they didn't have permission so right now players are doing /nucleus:back to avoid the broken permission if you could solve that or see if the back command from nucleus could have your backs features when installed that would be good (if any of that made sense) if nucleus is installed it could say "if a player uses /back that's nucleus but if /back/return portal/p then project portals." I'm sorry if this makes little sense it's 8am I've been up all night but I'll reply asap and improve this message hopefully :s thanks for a fast reply tho

**Comment by NoxIceCat** [comment]
To greatly improve upon my previous mess of a comment (my apologies) I require the back command to not override the nucleus version of the command/s if posible :) 

Again sorry bout the lack of thought and detail in my last comment lol

**Comment by trentech** [comment]
Added in latest
