### ISSUE TITLE
Door portal does not close itself after using it

### ISSUE THREAD

**Issue by SansIsTyping** [trentech/ProjectPortals#28]
Plain and simple in the title.

**Comment by trentech** [comment]
Not 100% but you saying player is still teleported if walk into a closed door?

**Comment by SansIsTyping** [comment]
@trentech practically yes. If you have a closed door in the middle of nowhere, and you walk behind it, you get teleported.

**Comment by trentech** [comment]
Got it. Thanks for the report. Will leave this open until issue is resolved

**Comment by SansIsTyping** [comment]
Brilliant :D

**Comment by trentech** [comment]
b08e835351af04cd95198a7ca6c50e89ed232c81

**Comment by trentech** [comment]
This change might also enable the use of trap doors, and doors from mods as well, however that hasn't been tested
