### ISSUE TITLE
pjp.portal.interact perm node doesn't work

### ISSUE THREAD

**Issue by SansIsTyping** [trentech/ProjectPortals#29]
Even with the perm node granted, users (who don't have default permissions set to 1 in PEX 2.0) cannot use portals. Please note I am using PermissionsEX **2.0**.

Here's a list of the Sponge plugins that are currently installed:
![uNAi6u9.png](http://i.imgur.com/uNAi6u9.png)

**Comment by trentech** [comment]
Is advanced_permissions set to false in config?

**Comment by SansIsTyping** [comment]
@trentech It is set to false, yes

**Comment by trentech** [comment]
I'm not able to produce this problem.

**Comment by SansIsTyping** [comment]
Crap. I'll see what I can do and then I'll get back to you.
