### ISSUE TITLE
Command prefix to prevent possible conflicts

### ISSUE THREAD

**Issue by MarkL4YG** [trentech/ProjectPortals#3]
Hey, I noticed the commands to add portals are e.g.

"/door", "/plate", "/button" or similar.

This may cause conflicts with other plugins

You may want to add a prefix for your plugins commands.

Example:
"/pjp door" or "/pjp button", ... 

(I would give it a try then as it seems like a neat plugin to have ':D )

**Comment by trentech** [comment]
https://github.com/trentech/ProjectPortals/issues/2
