### ISSUE TITLE
Bungee

### ISSUE THREAD

**Issue by Mattabase** [trentech/ProjectPortals#31]
/portal create -b Nether

I am using that command in an attempt to make a portal to another server, it is telling the server does not exist or is not loaded. What might I doing incorrectly?

**Comment by trentech** [comment]
You're missing the name parameter

/portal create {name} -b Nether

I will also direct you to https://github.com/trentech/HelpMe/releases

This plugin gives more information for registered commands that have HelpMe integrated into them. Most of my plugins are supported. check out the wiki page for more information

**Comment by Mattabase** [comment]
Thank you very much
