### ISSUE TITLE
[1.10.2 / Sponge 5.1.0-BETA-1961 / pjp-5.1.0-0.13.6] Warps permissions seems works wrong

### ISSUE THREAD

**Issue by mister-man** [trentech/ProjectPortals#33]
Hallo together,
I found maybe a bug in the permission system. If you give a player the permission to use warps and list warps they can create new warps and delte,

Pex:
```
						"pjp.cmd.warp": 1,
						"pjp.cmd.warp.list": 1,
						"pjp.warps.lobby": 1,
						"pjp.warps.sft": 1,
						"pjp.warps.st1": 1,
						"pjp.warps.st2": 1,
						"pjp.warps.st3": 1,
						"pjp.warps.st4": 1,
						"pjp.warps.st5": 1,
						"pjp.warps.st6": 1,
```

If I remove the permission ""pjp.cmd.warp": 1", warps doest work at all. 
I get an debug log out of pex and it seems pex answer with the permission "pjp.cmd.warp.create" with 1, if I set ""pjp.cmd.warp": 1". But without it, warps doesnt work at all. 

Pex:
```
[12:44:45] [Server thread/INFO] [permissionsex]: Permission pjp.cmd.warp checked in [world=lobby, localport=25565, localhost=, localip=, remoteip=, dimension=minecraft.overworld] for user 1
[12:44:45] [Server thread/INFO] [permissionsex]: Permission pjp.cmd.warp.create checked in [world=lobby, localport=25565, localhost=, localip=, remoteip=, dimension=minecraft.overworld] for user 1
```

It seems that the check of the overall permission "pjp.cmd.warp" is checkt to early and the pjw dosn't check the single permissions "pjp.cmd.warp.create", "pjp.cmd.warp.remove", "pjp.cmd.warp.list", and "pjp.cmd.warp.other". 

If there is the same error by home,... is not tested by me.

Thanks for helping.

**Comment by COLDYY1** [comment]
Hello mister-man!

I agree with you. I recently discovered this internal bug myself. This is a problem with the plugin and should be stated as critical according to me. The only thing we can do Is to sit and wait for an hotfix for this types of errors.

Best Regards,
COLDYY1

**Comment by trentech** [comment]
unable to reproduce. Try updating to latest release
