### ISSUE TITLE
All portals stop working on server crash/restart. v0.13.6

### ISSUE THREAD

**Issue by ConquestReforged** [trentech/ProjectPortals#34]

**Comment by trentech** [comment]
Most likely server crash caused the database to become corrupted. Try removing the data file from the pjp config directory and recreate the portals

**Comment by ProxyNeko** [comment]
I've been having this same issue on server restarts on two of my servers but have not had it on my hub server or another modded server using the exact same version with fresh saves/configs edited as needed and each time theres no error or anything to indicate what it was the portals are just gone after a timed restart. (Not getting crash problems on the one server I do crash with world edit though)

**Comment by trentech** [comment]
unable to reproduce. Try updating to latest release
