### ISSUE TITLE
BungeeCord Portal

### ISSUE THREAD

**Issue by Zangoran** [trentech/ProjectPortals#35]
When attempting to execute the command  ' /portal create PortalName BungeeServerLocation -b ' nothing happens. No error in the console, Nothing in the logs. Is there something I am missing? Thanks!

**Comment by Huene** [comment]
Zangoran I can't seem to find any documentation on how to use this feature anywhere, how did you find out about that -b? I need to look over the syntaxes

**Comment by Zangoran** [comment]
I don't exactly remember where I read it. It might have been in the command help. Or some documentation somewhere. I still haven't gotten it to work so.

**Comment by trentech** [comment]
You need SpongyCord, although it should be throwing an error without it

**Comment by Zangoran** [comment]
@trentech Thanks! Will give it a shot later.
