### ISSUE TITLE
Crash on save portal

### ISSUE THREAD

**Issue by JamieS1211** [trentech/ProjectPortals#4]
Log - http://pastebin.com/bT0SuUvR
Sponge - spongeforge-1.8.9-1855-4.1.0-BETA-1310
ProjectPortals - v0.10.43

**Comment by trentech** [comment]
Their redstone wire nearby?

**Comment by JamieS1211** [comment]
No but pistons are

**Comment by JamieS1211** [comment]
Rapid response. Kudos to you

**Comment by trentech** [comment]
I'm on my phone so it's difficult to read the log. I'm at work, I'll take a closer look when I get home, but I see a lot of errors referring to redstone wire. It could be the pistons..

**Comment by JamieS1211** [comment]
Ok, thanks very much!

**Comment by trentech** [comment]
So far I've been unable to duplicate or determine the cause for this error. Does it still occur?

**Comment by trentech** [comment]
No response, Not able to replicate, Issue part of old build
