### ISSUE TITLE
Could not pass FMLServerStartedEvent to Plugin

### ISSUE THREAD

**Issue by EmanYm** [trentech/ProjectPortals#41]
I only noticed this starting in the last few days after a scheduled server restart initiated by my host.
Console log: http://pastebin.com/Sa7g2727 (paste had expired)
I have re-downloaded the mod and double checked my config.  All seems well on my end.
Do you suggest I down grade it a version and see if it still does this?  I can go back as far as 0.13.3.

Edit:
I should mention that all of the modules I have set to `true` work fine with no error in the console.

**Comment by EmanYm** [comment]
Bump

**Comment by ziceptor** [comment]
http://pastebin.com/ZztXPJTW

**Comment by EmanYm** [comment]
Has anything been done on this yet?

**Comment by trentech** [comment]
Only current way to fix this is deleting the data file in the config directory and starting over, until I come up with a solution for fixing broken/corrupt data

**Comment by ziceptor** [comment]
Thank you!

**Comment by EmanYm** [comment]
Are there plans on adding MySQL support for database storage?

**Comment by EmanYm** [comment]
>Only current way to fix this is deleting the data file in the config directory and starting over, until I come up with a solution for fixing broken/corrupt data

Will I have to do this every day?  My host does a system initiated server restart every night around midnight server time, and every morning when I look at the console I get the [same error](http://pastebin.com/WAKU7JAu).

How is the data being corrupted?

**Comment by trentech** [comment]
Yes MySQL support is coming

You using any special block types for your portals like from mods or something? Sponge's serialization is a huge pain and seems to break frequently when mods get thrown in the mix. Been trying to come up with a solution to fix this for quite sometime but no luck yet.

**Comment by EmanYm** [comment]
So far I have only used buttons (which stop working after I leave that dimension) and signs (which seem to retain the pjp data even after a restart).

The only attempt at a portal was abandoned.  It created the nether portal behind it, and didn't take me to the destination I wanted it to.  I ended up at the set coordinated in the nether instead.
