### ISSUE TITLE
chat menu issue

### ISSUE THREAD

**Issue by EmanYm** [trentech/ProjectPortals#42]
When I click on "/portal create", or any of those menu items.  "Not enough arguments"
https://i.gyazo.com/1add95188172e0a26cb50eabfb0892eb.png
Nothing in console of chat as far as errors go.

I also want to know how to remove the Nether portal block from the portal I made. (#37)
https://i.gyazo.com/951a0ca216c191245764a6fb08d20d5e.png
The video you put on the SpongePowered page doesn't have the swirly portal block or the portal particles
also how to change the particles that drop where the portal is.  I would like to colour code my portals.

Edit:
I figured out the particle out of curiosity.  `/portal particle` isn't really documented anywhere as a command except as a permission node.

**Comment by ktole1999** [comment]
in 1.10 the purple portal block was removed from player access meaning it does not have an id for you to ban it.

**Comment by EmanYm** [comment]
I don't want to ban it.  I was wondering why the nether portal was put in when I created a portal, but it didn't appear in the example video...and how I can make it to not appear in the future portal creation.

I feel that the swirly purple blob the colour and consistency of purple ketchup (http://pbs.twimg.com/media/B9vtKQSIEAELGO9.png) and horizontal-flowing particles take away the aesthetics I was going for.

**Comment by trentech** [comment]
You can change the default particle in the pjp config

**Comment by trentech** [comment]
Also purple ketchup...terrible

**Comment by ktole1999** [comment]
sorry for misreading that.

**Comment by EmanYm** [comment]
>You can change the default particle in the pjp config

It looks like I deleted the gyazo images, but I was still getting the default nether portal behavior (purple swirls and portal particles) behind  the chosen PJP particle regardless of config settings back when I first posted this.  I haven't played around with it much since.  I think it's been updated a couple times since, so it might be worth the effort to play around.


Unrelated and off topic:
>Also purple ketchup...terrible

Yea, back in the early to mid 90's there was purple and green ketchup.  I heard rumors there was even blue, yellow and orange in parts of the United States (Red, orange, yellow, green, blue and purple -
 supposedly released on Gay-Pride Day 1995).  Google "purple Ketchup"

**Comment by trentech** [comment]
Oh I think I get what your saying now, and I remember fixing that at some point. My releases are behind. I got caught up favoring development on the 6.0.0 branch. I need to back port my changes. 

Yeah I know what your talking about. I grew up in the 90s in the states. Just saying its terrible.

**Comment by EmanYm** [comment]
I guess once you get the back ports caught up you can close this.  I'm not in any rush at this point.

**Comment by EmanYm** [comment]
Any luck getting the backlog of releases sorted out?

**Comment by trentech** [comment]
Backported all changes to 5.x, you'll want to remove HelpMe and SpongyCord from your servers if you have them and add https://github.com/trentech/ProjectCore/releases
