### ISSUE TITLE
Error occurred while executing command

### ISSUE THREAD

**Issue by EmanYm** [trentech/ProjectPortals#43]
The error:
http://pastebin.com/9pG0fMyj

I have also tried these
`/portal destination <PortalName> <x> <y> <z>` (and with ,) and got a "Too many arguments!" message
`/portal destination <world> <x> <y> <z>` (and ,)and got a "too many arguments!"
`/portal destination <portal name> <world:x,y,z>` and got an error
There were others I tried.  None are working

Minecraft 1.10.2
Spongeforge 2147
PJP 0.13.6

Edit:
Looking at the commits on 0.13.6 I see there is a 0.13.7 that says it fixes this issue, but it's not in your releases on here.

**Comment by trentech** [comment]
`/portal create <name> <world> -c <x,y,z>`
