### ISSUE TITLE
Feature request: Portal types destination

### ISSUE THREAD

**Issue by TomberWolf** [trentech/ProjectPortals#44]
Could you add destination coordinates for portal types?

Similar to this plugin:
https://dev.bukkit.org/projects/portal-destinations-redirection

**Comment by trentech** [comment]
This already exists using the -c flag

**Comment by TomberWolf** [comment]
So all portal that were created by players will automatically warp to a specific coordinate?

**Comment by TomberWolf** [comment]
Yes... no...?

**Comment by ktole1999** [comment]
nether portal pathing is broke per minecraft.

**Comment by TomberWolf** [comment]
Has nothing to do with my request.

**Comment by ktole1999** [comment]
this is what i was responding to. there is a mod called netherportalfix that resolves this issue but it does not work with sponge.

@TomberWolf So all normal nether portals that were created by players will automatically warp to a specific coordinate?

**Comment by TomberWolf** [comment]
@ktole1999 That would be what I want to, yes. The spigot plugin I've linked to in the first post does exactly what I want to.

It makes it possible to have a common "nether-tower" for example in the overworld as an entrance to the nether for all players (just an example for many scenarios).
