### ISSUE TITLE
Custom Permission Nodes

### ISSUE THREAD

**Issue by EmanYm** [trentech/ProjectPortals#45]
Just curious if I can do something like this:

example warp/portal names:
donator.#
staff.helper.#
staff.mod.#
player.#

Permission nodes (same nodes with 'portal'):
pjp.warps <Access to all warps/portals
pjp.warps.donator <gives access to all 'donator' warps/portals
pjp.warps.donator.# <access to specific number donator warp/portal
pjp.warps.staff <all 'staff' warps/portals
pjp.warps.staff.mod <only access to 'mod' warps/portals
pjp.warps.staff.helper.# < Specific number helper warp/portal only

I guess this would also apply to pjp.worlds.{worldName} for anyone that has multiple worlds

**Comment by trentech** [comment]
PJP perms are a bit confusing right now. How about instead I add -p flag that lets you set your own portal permission nodes?

**Comment by EmanYm** [comment]
If you think that would make it easier to make rank-specific nodes and stop basic players from gaining access to staff only areas.

**Comment by trentech** [comment]
I don't plan on changing those permissions, just portal interaction permissions

**Comment by trentech** [comment]
I implemented this change in the 6.x builds. If you want to test it you can find it here. The flag is -n, forgot -p was already being used

http://trentech.org/jenkins/job/Project%20Portals/
