### ISSUE TITLE
Why do I get the error "world does not exist"?

### ISSUE THREAD

**Issue by dpisarenko** [trentech/ProjectPortals#5]
I want to create a portal in one of the worlds and type in the following command

`/portal create portalAB 2016_05_30_worldB -c -128,81,-32`

I get the error `2016_05_30_worldB` doesn't exist.

![Error message](http://i.imgur.com/biaZJQ3.png)

But the world `2016_05_30_worldB` appears in the list of worlds in Minecraft and there is a corresponding directory in the Minecraft folder (see screenshots below).

![List of worlds](http://i.imgur.com/tTtQ1XN.png)

![World in the Minecraft directory](http://i.imgur.com/h2uL77F.png)

What do I need to do in order for the plugin to recognize the world?

I'm using `projectportals-4.1.0-0.10.43.jar` and `spongeforge-1.8.9-1890-4.1.0-BETA-1320.jar`.

**Comment by dpisarenko** [comment]
I thought that I may solve the problem by installing a multiworld plugin. I found [ForgeEssentials](https://github.com/ForgeEssentials/ForgeEssentials/wiki/Multiworld), but it's only compatible with Minecraft 1.8, whereas ProjectPortals seems to require Sponge 4.1.0, but for Minecraft 1.8 there is [no Sponge 4.1.0](http://files.minecraftforge.net/maven/org/spongepowered/spongeforge/index_1.8.html).

**Comment by trentech** [comment]
Not able to replicate the problem. Have your single player world been renamed in the past?

**Comment by dpisarenko** [comment]
Yes, but the problem persists even after I tried it on a new world (which hasn't been renamed). I also tried to use world names without underscores.

Question: Can I use ProjectPortals without a multiworld plugin at all?

ProjectPortals works, if I install ProjectWorlds and then use ProjectPortals on the worlds created with ProjectWorlds.

**Comment by trentech** [comment]
As I said, PJP doesn't require a multiworld plugin to work. If you have PJW installed, enter /world list to see what comes up. There might be something going on were not seeing. Also what version of Forge are you using? I'd like to rule out any version mismatches with SpongeForge.

**Comment by dpisarenko** [comment]
>  Also what version of Forge are you using?

See below. I'll provide more information about this problem a bit later.

![Screenshot](http://i.imgur.com/nFAMzwK.png)

**Comment by trentech** [comment]
Yeah I'm not seeing any reason for your problem. Any chance you could zip your world and send it to me, if it's not too large? Also try updating to the latest SpongeForge build 1366

**Comment by dpisarenko** [comment]
> Any chance you could zip your world and send it to me, if it's not too large?

I repeated the whole process with only ProjectPortals mod installed. Here are the results:

* [Steps to reproduce](http://altruix.cc/wp-content/uploads/2016/05/2016_05_30_portalsProblem.pdf)
* [Archive with 2 worlds I created while reproducing the error](http://altruix.cc/wp-content/uploads/2016/05/2016_05_30_worlds.zip) (7 MB)

**Comment by dpisarenko** [comment]
> Also try updating to the latest SpongeForge build 1366

I get the same result with `spongeforge-1.8.9-1890-4.1.0-BETA-1366.jar`.

**Comment by dpisarenko** [comment]
> You'd have to move one of the game saves inside the other. 

If you know, how to do this programmatically (from inside a Sponge plugin), please tell me.

But it's not a high priority issue because I'm fine with the ProjectWorlds solution for now. So you may close the issue.

**Comment by dpisarenko** [comment]
And yes - thanks for fast answers :)

**Comment by trentech** [comment]
Well in a perfect world, it would have worked the way I described it, however Sponge does not understand how to handle world name and id conflicts and I've been struggling since the beginning to resolve this without making a complete mess of things. Its something I'm hoping the guys at Sponge will be able to take care of from within the Sponge implementation because the utilities needed to perform this task without ridiculous workarounds that break all the time, are not exposed in the Sponge API.
