### ISSUE TITLE
Bungee portal

### ISSUE THREAD

**Issue by EmanYm** [trentech/ProjectPortals#51]
>/portal create play world -b
I notice it [posts the instruction to type "/portal save" twice](https://i.gyazo.com/36d288943251532a77f38846a58d92e4.png)
Make the frame
/portal save
fill in the space I want the portal to be
/portal save
standard nether portal appears in the frame I made
step into the portal
"You do not have permission to use portals"

Checked the permissions, `pjp.servers.play` and `pjp.portal.play` are both inherited down the line from the "trainer"
The destination server is named `play` in bungeecord
The default world is named `world`

According to #31, this should make a portal to spawn point on the "play" server
`/portal create play world -b`
(Unless it should actually be `/portal create <portal name> <world name> -d <server name>`)

What am I doing wrong

SpongeVanilla 5.2.0 build 385
ProjectPortals 0.13.6
SpongyCord 1.1.1
LuckPerms 3.2.8 build 217

EDIT:
I didn't have `advanced-permissions` set to true.  I changed it to true and restarted the server.  Now it just takes me to the spawn point of the server I'm currently on and I get [this error](https://hastebin.com/axedupokit.md) in the console.

Unrelated, `/help pjp` returns nothing.

**Comment by trentech** [comment]
If the server name is play, then it should be `/portal create play play -b`
Because the plugin can't directly talk to the other server you can't specify a location of where you are spawned. It basically just logs you out of one server and logs you into the other. Where you spawn is determined by the other servers setup.

**Comment by trentech** [comment]
`/portal create <name> <server> -b`

**Comment by EmanYm** [comment]
I see.  Let me test...

So I made the frame, entered the command above and it worked.
"Kicked whilst connecting to play:  This server requires FML/Forge blah blah blah"
Since my hub is vanilla I expected that.  It appears to be working, however.

**Comment by EmanYm** [comment]
Is it possible to set the portal to a certain world on the target server?
For example server "build", world "Test"

**Comment by EmanYm** [comment]
Except now I can't make a normal portal. x_x
every time I try to make a portal it asks me to click the center instead of asking me to make the frame first.

**Comment by trentech** [comment]
You've disabled legacy_builder in the config. Set to true. Or click the center of the portal. It was my attempt at a one click system. You build the frame, then run the /portal create command, and click inside the portal frame. It's a bit unstable right now, sometimes it works, sometimes it doesn't
