### ISSUE TITLE
java.lang.IllegalStateException: Calling Timings from Async Operation

### ISSUE THREAD

**Issue by EmanYm** [trentech/ProjectPortals#52]
[This](https://hastebin.com/uvafepuyic.md) happens when I try to go through a bungee portal.

The first cross-server portal I made worked fine during testing, then I made a second one, and that's when both stopped working.

**Comment by trentech** [comment]
OK update to latest release, remove SpongyCord (and HelpMe if you have it), and add this https://github.com/trentech/ProjectCore/releases

**Comment by EmanYm** [comment]
What if SpongyCord is needed for something else.  I assume you just removed dependency from PJP in favour of your Core?

**Comment by trentech** [comment]
Shouldn't cause any conflicts
