### ISSUE TITLE
particles not showing up

### ISSUE THREAD

**Issue by EmanYm** [trentech/ProjectPortals#53]
It seems that the redstone particle is not visible, no matter what colour I make it.
PJP 0.13.7

**Comment by trentech** [comment]
Oh i think there's an error in the instructions given. It's REDSTONE not REDSTONE_DUST

**Comment by trentech** [comment]
Yeah I'm a little confused, My tests show both REDSTONE_DUST and REDSTONE both work.

**Comment by EmanYm** [comment]
I'm a derp.  I have redstone particals turned off in Optifine.
More derp sprinkles for my eedjit ice cream!
