### ISSUE TITLE
Two config files

### ISSUE THREAD

**Issue by EmanYm** [trentech/ProjectPortals#54]
Since updating there are now two config files.
I assume `pjp.conf` is the currently used file and I can safely delete `config.conf`

Portals 0.13.7

**Comment by trentech** [comment]
Yeah the new config manager i wrote changes the config naming standard. You can safely delete it the old or rename it to pjp.conf

**Comment by EmanYm** [comment]
I just opened them both, changed the settings in the new one to match the old, then deleted the old.  Problem solved!
