### ISSUE TITLE
Portal ignores direction

### ISSUE THREAD

**Issue by cate776** [trentech/ProjectPortals#56]
PJP: 5.2.0-13.7
SpongeForge: 1.10.2-2281-5.2.0-BETA-2363
Minecraft Forge: 12.18.3.2297

When creating a portal, the direction specified with the -d flag is ignored and the direction is always East.

**Comment by EmanYm** [comment]
https://github.com/NucleusPowered/Nucleus/issues/870
This might be a sponge or forge issue.

**Comment by kalek3** [comment]
è vero

**Comment by bhi-elliot** [comment]
This still seems to be an issue as of:

Java version: 1.8.0_151-b12
minecraft server.1.12.2
forge 1.12.2 14.23.1.2554 universal
spongeforge 1.12.2 2529 7.0.0 BETA 2746
project core 7.0.0 0.2.1 b31
project portals 7.0.0 0.14.0 b29

**Comment by Golbinex** [comment]
Commited pull request, should be fixed soon.

**Comment by trentech** [comment]
resolved
