### ISSUE TITLE
java.sql.SQLDataException: Data too long for column 'Data' at row 1

### ISSUE THREAD

**Issue by EmanYm** [trentech/ProjectPortals#59]
When I try to make a 20x15 portal I get [this error](https://hastebin.com/cicuhaxaki.tex).
max blocks is 500 in the config

Would you be willing to split the information into different columns for MySQL so it's easier to view?

PJP 0.13.7
SpongeVanilla 5.2.0-Beta387

**Comment by trentech** [comment]
The data in that column is a serialized DataContainer. Attempting to split it would cause my harm than good. I do believe I have a fix for this though.

**Comment by trentech** [comment]
Resolved
