### ISSUE TITLE
Project Portal

### ISSUE THREAD

**Issue by Sclane1** [trentech/ProjectPortals#60]
Every Time when i create a Portal with Project Portals 7.0.0-0.14.0 i get a Error from Sponge

Ingame:
Error occurred while executing command:
org.spongepowered.api.data.DataContainer.createNew()Lorg/spongepowered/api/data/DataContainer;

Server Console: (pls read from down to top)
29.06 12:24:40 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zhn000(MinecraftServer.java:3932) [MinecraftServer.class:?] 29.06 12:24:40 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:241) [SpongeImplHooks.class:1.10.2-2281-5.2.0-BETA-2379] 29.06 12:24:40 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?] 29.06 12:24:40 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121] 29.06 12:24:40 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121] 29.06 12:24:40 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?] 29.06 12:24:40 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjh000(SourceFile:539) [fl$1.class:?] 29.06 12:24:40 [Server] INFO at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-2281-5.2.0-BETA-2379] 29.06 12:24:40 [Server] INFO at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:162) [CauseTracker.class:1.10.2-2281-5.2.0-BETA-2379] 29.06 12:24:40 [Server] INFO at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2281-5.2.0-BETA-2379] 29.06 12:24:40 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?] 29.06 12:24:40 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?] 29.06 12:24:40 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) ~[me.class:?] 29.06 12:24:40 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) ~[me.class:?] 29.06 12:24:40 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?] 29.06 12:24:40 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) ~[SpongeCommandManager.class:1.10.2-2281-5.2.0-BETA-2379] 29.06 12:24:40 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.10.2-2281-5.2.0-BETA-2379] 29.06 12:24:40 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.10.2-2281-5.2.0-BETA-2379] 29.06 12:24:40 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:182) ~[ChildCommandElementExecutor.class:1.10.2-2281-5.2.0-BETA-2379] 29.06 12:24:40 [Server] INFO at com.gmail.trentech.pjp.commands.portal.CMDSave.execute(CMDSave.java:48) ~[CMDSave.class:?] 29.06 12:24:40 [Server] INFO at com.gmail.trentech.pjp.portal.LegacyBuilder.build(LegacyBuilder.java:84) ~[LegacyBuilder.class:?] 29.06 12:24:40 [Server] INFO at com.gmail.trentech.pjp.portal.PortalService.create(PortalService.java:144) ~[PortalService.class:?] 29.06 12:24:40 [Server] INFO at com.gmail.trentech.pjp.portal.Portal.serialize(Portal.java:293) ~[Portal.class:?] 29.06 12:24:40 [Server] INFO at ninja.leaping.configurate.ConfigurationNode.setValue(ConfigurationNode.java:402) ~[spongeforge-1.10.2-2281-5.2.0-BETA-2379.jar:1.10.2-2281-5.2.0-BETA-2379] 29.06 12:24:40 [Server] INFO at org.spongepowered.common.config.DataSerializableTypeSerializer.serialize(DataSerializableTypeSerializer.java:41) ~[DataSerializableTypeSerializer.class:1.10.2-2281-5.2.0-BETA-2379] 29.06 12:24:40 [Server] INFO at org.spongepowered.common.config.DataSerializableTypeSerializer.serialize(DataSerializableTypeSerializer.java:59) ~[DataSerializableTypeSerializer.class:1.10.2-2281-5.2.0-BETA-2379] 29.06 12:24:40 [Server] INFO at com.gmail.trentech.pjp.portal.Portal$Local.toContainer(Portal.java:214) ~[Portal$Local.class:?] 29.06 12:24:40 [Server] INFO java.lang.NoSuchMethodError: org.spongepowered.api.data.DataContainer.createNew()Lorg/spongepowered/api/data/DataContainer; 29.06 12:24:40 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'portal save' for source EntityPlayerMP['Sclane1'/3281, l='EmpireLobby', x=0.33, y=146.00, z=-0.48]: org.spongepowered.api.data.DataContainer.createNew()Lorg/spongepowered/api/data/DataContainer;

Project Core 7.0.0-0.1.0
Project World 7.0.0-0.12.0

Core and World work fine on Server, but we want a portal between lobby and another world.
I hope you can help us.

**Comment by trentech** [comment]
That's for Sponge 7.0.0. You need the build for 5.2.0
