### ISSUE TITLE
When world is unloaded and loaded again, the portal disappears.

### ISSUE THREAD

**Issue by tests04** [trentech/ProjectPortals#66]
Before
http://imgur.com/UGhu66B
↓
Unload this world.(with Project World Plugin)
Enter the portal as it is ...
http://imgur.com/cn3YNIl
↓
The portal disappears.
http://imgur.com/lLPzVnn

The same phenomenon does not occur in "Nether".

-Plugin Info-
forge-1.11.2-13.20.0.2315
spongeforge-1.11.2-2315-6.1.0-BETA-2438.jar

project core-7.0.0-0.1.0.jar
project.portals-5.2.0-0.13.7.jar
project.worlds-6.1.0-0.12.0.jar

**Comment by EmanYm** [comment]
How do you have your portals stored?  Flat file or MySQL?

**Comment by tests04** [comment]
It is probably MySQL.
"pjp.mv.db" exists in "server-root\config\pjp".

**Comment by trentech** [comment]
> project core-**7.0.0**-0.1.0.jar
project.portals-**5.2.0**-0.13.7.jar
project.worlds-**6.1.0**-0.12.0.jar

A lot of mismatches here.

This version is now unsupported. If problem occurs on latest version, please open a new ticket
