### ISSUE TITLE
Portal creation with bungeecord doesn't work

### ISSUE THREAD

**Issue by BakermanLP** [trentech/ProjectPortals#67]
Hello,

I am trying to setup a bungeecord portal with Project Portals.

My setup is :
3x Forgeserver:
- forge-1.11.2-13.20.1.2393-universal.jar
- spongeforge-1.11.2-2393-6.1.0-BETA-2468.jar
- SpongyCord-1.1.1.jar
- project core-6.1.0-0.1.0.jar
- project portals-6.1.0-0.14.0.jar

Bungeecord Server:
Waterfall (latest version), plugins:
- SpongePls.jar
- BungeeChat-1.3.3_117.jar
- BungeeTabListPlus-2.7.0.jar

I try to create a portal for bungeecord with the following command:
/portal create toeasy easy -b

toeasy = Portal name
easy = servername in bungeecord

Error Message:
Unknown short flag b specified\ncreate toeasy easy -b

What I am doing wrong, or do I miss something. Switching to the other server with the “/server easy” command is working.

Thanks for reply

Michael (aka BakermanLP)

**Comment by trentech** [comment]
This version of PJP is no longer supported. If the issue still occurs on latest version, please open another ticket
