### ISSUE TITLE
Problem with project portals permissions

### ISSUE THREAD

**Issue by ErnestoNoihara** [trentech/ProjectPortals#69]
Hi i have some problems with the permissions which is the perm that lets user to travel to other worlds i have also instaled the project world so idk if is a permission of that plugin or of this plugin becouse i tried with the perm pjp.portal.interact and the pjw.cmd.world.teleport but still not working pls need help with this
Software info:
spongeforge-1.11.2-2315-6.1.0-BETA-2377
project.portals-5.2.0-0.13.7
project.worlds-6.1.0-0.12.0
project.core-5.2.0-0.1.0

**Comment by trentech** [comment]
`pjw.worlds.<world>`
