### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by EmanYm** [trentech/ProjectPortals#71]
I get [this](https://hastebin.com/cokuwafavo.rb) when trying to list portals

I will also report this to Sponge

I was still able to remove the portal with no issue.

**Comment by trentech** [comment]
I think this commit broke something https://github.com/SpongePowered/SpongeAPI/commit/c4ead797895918d375855bb6124bc34786e00839

I'm pretty confused by the whole thing because the method clearly exists.
