### ISSUE TITLE
Setting the portal location to 'bed' sends player to world spawn instead of the player's spawn (bed)

### ISSUE THREAD

**Issue by zhaey** [trentech/ProjectPortals#74]
https://github.com/trentech/ProjectPortals/blob/b6cb1dc8a16a25833db8259f701b4eaae039fba0/src/main/java/com/gmail/trentech/pjp/portal/features/Coordinate.java#L72

This line gets the world spawn, not the player's spawn. I don't know if there's an API method to retrieve the player's spawn, but I remember from an old Bukkit plugin that they just stored the location when anyone slept in a bed.

**Comment by zhaey** [comment]
https://jd.spongepowered.org/4.1.0/org/spongepowered/api/data/manipulator/mutable/entity/RespawnLocationData.html

I'm pretty new to Sponge, but it looks like this might be the endpoint you're looking for.

**Comment by trentech** [comment]
Bed spawns haven't been implemented due to issues with it RespawnLocationData returning an empty map. Haven't done any testing on Api 7 yet.

**Comment by trentech** [comment]
This has been resolved
