### ISSUE TITLE
1.12.2 - Can't create portal

### ISSUE THREAD

**Issue by Krosta8** [trentech/ProjectPortals#75]
Hello,
I found out an error, when I tried to create a new portal on Sponge 1.12.2. I can run command /portal create, than the first /portal save and the second /portal save (the final step) caused an error.
https://pastebin.com/TSAe2QB9

**Comment by aWitch-Doctor** [comment]
Same issue for me, I have the following on the server.
MC 1.12.2
Sponge Vanilla 1.12.2-7.0.0 Build 342
Nucleus 1.2.0 PR2
Project Portals 7.0.0-0.14.0
Project Core 7.0.0-0.2.0
Luckperms 3.4.18
Grief Prevention 1.12.1-4.3.0.450

I get this error: https://hastebin.com/enuqexofof.rb

**Comment by aWitch-Doctor** [comment]
It works with MC 1.12.1 and Sponge Vanilla 1.12.1-7.0.0-BETA-320. Not sure what version it breaks on though.

**Comment by Krosta8** [comment]
I quickly read about some changes with "Cause event" or something like that on version 1.12.2.

**Comment by aWitch-Doctor** [comment]
Mkay, The newest version of sponge and nucleus you can use and still get project portals to work are:
Sponge Vanilla 1.12.1-7.0.0-BETA-323 (I didn't try Sponge Forge)
Nucleus Version 1.2.0 pre-release 1.2 (for 1.12.1)

In Sponge Vanilla 1.12.1-7.0.0-BETA-324 things break with PJP and Nucleus Version 1.2.0 pre-release 1.2 (for 1.12.1) is the newest version of nucleus that will run on Sponge Vanilla 1.12.1-7.0.0-BETA-323.
