### ISSUE TITLE
Conflict with tinkers construct

### ISSUE THREAD

**Issue by wanderingmage** [trentech/ProjectPortals#76]
Server crashes when using tinkers construct in conjunction with project portals plugin.

[crash-2017-10-10_20.29.46-server.txt](https://github.com/trentech/ProjectPortals/files/1376075/crash-2017-10-10_20.29.46-server.txt)

Will also be submitting to The authors of tinkers as well.

**Comment by Krosta8** [comment]
I think, that it is not because of Tinkers Construct, because I have both installed and "without any problem".

I have problem just with portals on server start. Every time it delete all created portals. Do you have this problem too?

**Comment by wanderingmage** [comment]
Same, but when portals is installed, tinkesr becomes useless. Can't use anything from tinkers without crashing the server. I remove portals plugin and problem goes away.

**Comment by trentech** [comment]
I don't see anything here related to PJP directly. I could be some sort of conflict between SpongeForge and Tinkers. I would suggest submitting a bug report to Sponge and Tickers.
