### ISSUE TITLE
Portals deleted after server restart

### ISSUE THREAD

**Issue by fboyd** [trentech/ProjectPortals#80]
@trentech 
I didn't want to make a duplicate Issue, but I have the exact problem from a closed issue.  Let me give the details.  Your commit references in the closed issue is for v7 API while I am running v5.
See info below.  Clean brand new server build and install.  No pre-existing database.
Server:
Java:
> java version "1.8.0_66"
> Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
> Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

MineCraft &Mods Versions:
> MineCraft 1.11.2
> spongeforge-1.11.2-2476-6.1.0-BETA-2715
> forge-1.11.2-13.20.1.2476
> justenoughdimensions-1.11.2-1.6.0-dev.20171107.235423 [JED Latest ](https://masa.dy.fi/tmp/minecraft/jed/1.6.0-dev/)
> projectcore-5.2.0-0.1.5
> projectportals-5.2.0-0.13.8

JED Command to create Dimension
> /jed dimbuilder clear
> /jed dimbuilder dimtype 1100 tmpname _dim1100 false WorldProviderSurfaceJED
> /jed dimbuilder set name Creative_1100
> /jed dimbuilder set generatorName default
> /jed dimbuilder set RandomSeed -4799909556600174584
> /jed dimbuilder set keepInventory true
> /jed dimbuilder set mobGriefing false
> /jed dimbuilder set Difficulty 1
> /jed dimbuilder set SpawnX 732
> /jed dimbuilder set SpawnY 65
> /jed dimbuilder set SpawnZ 306
> /jed dimbuilder create-as 1100

On my desktop I installed Minecraft Launcher, Java 8.144, and installed the same Forge and mods except of course Sponge don't need on the client side.

The reason I am using the older Forge is for Sponge, because I am trying to use GriefPrevention and LuckPerms, and of course ProjectPortals.  v7 of Sponge from what I saw is on a much older version of Forge which is incompatible with mods I am using.
But in this case, I simply used the bare minimum.
I create the portals between dimensions just peachy and they work fine.  I logout / login and they are fine.  I restart the server, boom gone, run a `portal list` and it is empty.

The server restart I get this right after it is `*done*`
https://pastebin.com/2BAEGKRj

I'm not a Java programmer so I'm no help there, but I can put my server on the net if you want to see for yourself, but I'd appreciate any help, I love this plugin, and I just got Matti, the dev of JustEnoughDimensions to fix up that mod to work with Sponge.

Let me know whatever I can do to help, I'd appreciate any help in resolving this.
Thanks!
-Frank

**Comment by guuslieben** [comment]
Having this same issue with PP. 
Also occurs with Project Worlds to handle worlds, rather than JED. 

_Subscribed to issue._

**Comment by AlwaysQuads** [comment]
Same issue here on FTB Beyond, it seems to save the portals after I wipe the databases and do it fresh. Any other portals added after a reboot are gone the next reboot.

**Comment by NHDriver4** [comment]
It appears that this happens is a world is unloaded and then reloaded. Keeping the portal in the spawn protected area and keeping spawn loaded prevents the portal from disappearing. It seems as though the portal is not created properly if the world is loaded as a result of porting to it.

**Comment by kencinder** [comment]
Yes as soon as a world is unloaded, the portal breaks.

Workaround should be to set

```
# If 'true', this worlds spawn will remain loaded with no players.
        keep-spawn-loaded=true
```

in each world's dimension.conf

**Comment by shelbykauth** [comment]
Same issue.  For me, that work-around doesn't work.  I have those both set to true, and it still deletes the portals.

Also, we shouldn't have to make a work-around.  I was planning on making our local server have portals to a bunch of different worlds.  I may not have the resources to keep 5 dimensions loaded constantly.

But yeah, this issue renders the portals pretty much useless.  As every time I shutdown the server to add a plugin or a mod or because the computer it's running on needs a refresh, I would have to go back and remake all those portals.

(By the way, I'm on SpongeForge 2990 for Forge 2611.  projectworlds-7.1.0-0.12.2.jar, projectportals-7.1.0-0.14.3.jar, projectcore-7.0.0-0.2.1.jar, Nucleus-1.3.7-S7.0-MC1.12.2-plugin.jar, LuckPerms-Sponge-4.1.63.jar and about 20 mostly client-side mods).

**Comment by kencinder** [comment]
Yeah I noticed in certain dimensions, the above config settings don't do anything. Twilight Forest and Aether-Legacy dimensions stay loaded...but spawn does not, and thus no chunks are loaded when the world is empty...breaking not just these portals, but command blocks.

Even using a chunk loader like BetterChunkLoaders fails, as chunks are never loaded.

This is actually a Sponge issue based on that, as a chunkloader can't even function properly.

**Comment by trentech** [comment]
unconfirmed on an unsupported version of Sponge
