### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ziceptor** [trentech/ProjectPortals#86]
https://gist.github.com/ziceptor/ab370d6c415c271901de97bf86b513aa

forge-1.12.2-14.23.1.2586-universal.jar
spongeforge-1.12.2-2586-7.1.0-BETA-2863.jar
projectcore-7.1.0-0.2.1.jar
projectportals-7.1.0-0.14.2.jar

**Comment by trentech** [comment]
Stop breaking my plugins 😄  

Can you describe the events prior to the crash?

**Comment by ziceptor** [comment]
:)
It happened when the server starts. Another log. [latest.log](https://gist.github.com/ziceptor/3def8c5c230e1e7a9112207db34d4064)

Today I updated the sponge and projectinventories-7.1.0-0.11.2.jar, projectportals-7.1.0-0.14.2.jar from ore.

**Comment by ziceptor** [comment]
Re-occurred when connecting the player to the server.

**Comment by ziceptor** [comment]
Server load https://gist.github.com/ziceptor/d3795b3511c7f18213ee37a3d9e453ca

**Comment by trentech** [comment]
This error doesn't make sense to me. Have you tried re-downloading the jar from ore? If that doesn't help try the latest jenkins build and let me know

https://trentech.org/jenkins/job/ProjectPortals/

**Comment by ziceptor** [comment]
I created a clean server. The failure occurs because of a conflict with the Nucleus. I've disabled all the modules from the Nucleus and ProjectPortals. But it still does [crash](https://gist.github.com/ziceptor/6bb5e05c03b4cd6008e0db8c918c7944).

forge-1.12.2-14.23.1.2586-universal.jar
spongeforge-1.12.2-2586-7.1.0-BETA-2868.jar
projectcore-7.1.0-0.2.2.jar
projectportals-7.1.0-0.14.2.jar

Always when you log on to the server.

**Comment by ziceptor** [comment]
Maybe it's related? https://gist.github.com/ziceptor/b56350e19bc6697ea00faf6e9f5e3ffb#file-gistfile1-txt-L6558

This error nucleus (@dualspiral please see) https://gist.github.com/ziceptor/b56350e19bc6697ea00faf6e9f5e3ffb#file-gistfile1-txt-L6556

**Comment by dualspiral** [comment]
Register your keys during pre-init by calling something from the class so that the static members are constructed at that time. The class is only loaded when someone calls for a key, which turns out to be me off the main thread, constructing the keys then. Because I’m only getting users, my async operation should be safe.

**Comment by jtripled** [comment]
I solved this by building this project with the line

Object ldKeys = Keys.BED_LOCATIONS;

added to Main.java in

onPreInitializationEvent()

as recommended by @dualspiral. I would have generated a pull request but this is fairly minor and I didn't feel the need to create a branch for this.

**Comment by trentech** [comment]
Try the latest release on Ore and report back

**Comment by jtripled** [comment]
Worked like a charm. Thanks for the great mod.

**Comment by ziceptor** [comment]
Yes, now it works. Many thanks!
