### ISSUE TITLE
Why dependency of SpongyCord (Spongee) when ProjectCore has its own BungeeClass

### ISSUE THREAD

**Issue by BrainStone** [trentech/ProjectPortals#88]
Since ProjectCore has it's own Bungee class, why is SpongyCord (Spongee) required for bungee portals?

**Comment by trentech** [comment]
It's not. It used to be.

**Comment by BrainStone** [comment]
When I try to create a bungee portal without it it tells me that I need spongee!

**Comment by trentech** [comment]
This was recently resolved here 3a223acc66c4939e0ed8bf0cf90ad477d97934be
Update to latest

**Comment by BrainStone** [comment]
It's not on Ore

**Comment by trentech** [comment]
It is
